"""Gamepad teleop for the ZERO panda workstation.

GENERATED by scripts/gen_bringup.py panda -- edit the generator, not this file.

Run the sim first:   ros2 launch zero_bringup panda.launch.py
Then this:           ros2 launch zero_bringup panda_teleop.launch.py

Starts joy_node plus the teleop node. autorepeat_rate matters: without it joy_node only
publishes on CHANGE, so holding a stick steady stops the messages and the arm stops with them.
It is set to match the teleop loop (50 Hz); at the default 20 it measured 14.4 Hz with 100 ms
gaps, which is input latency the operator feels as sponginess.

  LB = drive LEFT arm, RB = drive RIGHT arm (nothing held = frozen)
  left stick = X/Y     right stick = Z (up/down) + yaw (left/right)
  LT = left gripper, RT = right gripper (released open, pressed closed)
  A = return home      START = resync target to the measured pose

Check the axis map on a new pad with:  ros2 run zero_control joy_probe
"""

from launch import LaunchDescription
from launch.substitutions import PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description() -> LaunchDescription:
    bringup = FindPackageShare("zero_bringup")
    control = PathJoinSubstitution([bringup, "config", "panda_control.yaml"])
    teleop = PathJoinSubstitution([bringup, "config", "teleop.yaml"])
    return LaunchDescription([
        Node(package="joy", executable="joy_node", output="screen",
             parameters=[{"deadzone": 0.05, "autorepeat_rate": 50.0,
                           "coalesce_interval_ms": 5}]),
        Node(package="zero_control", executable="teleop", output="screen",
             parameters=[control, teleop]),
    ])
