"""Bring up the ZERO panda dual-arm workstation in MuJoCo under ros2_control.

GENERATED by scripts/gen_bringup.py panda -- edit the generator, not this file.

PIPELINE:
  1. robot_state_publisher puts the URDF on /robot_description. It goes through XACRO, which is
     load-bearing: the URDF's `mujoco_model` param uses `$(find zero_description)/...`, and only
     xacro expands that into an absolute path. mujoco_ros2_control does NOT resolve package://
     and dies with "MuJoCo model file 'package://...' does not exist!".
  2. mujoco_ros2_control's OWN ros2_control_node (not controller_manager's) loads the MJCF named
     by that param and starts the sim.
  3. Controllers spawn once the node is up -- joint_state_broadcaster first, or the position
     controllers activate with no state interfaces to read and immediately fault.

Cameras: 3 MJCF cameras are published because the URDF declares a matching <sensor> for
each (front, left_wrist, right_wrist). View them in RViz on /zero/<cam>/image_raw.

Run:  ros2 launch zero_bringup panda.launch.py
"""

from launch import LaunchDescription
from launch.actions import OpaqueFunction, RegisterEventHandler
from launch.event_handlers import OnProcessStart
from launch.substitutions import Command, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare

CONTROLLERS = ['joint_state_broadcaster', 'left_arm_controller', 'left_gripper_controller', 'right_arm_controller', 'right_gripper_controller', 'left_finger_joint1_ft_broadcaster', 'left_finger_joint2_ft_broadcaster', 'right_finger_joint1_ft_broadcaster', 'right_finger_joint2_ft_broadcaster']


def _preflight(context):
    """Refuse to start if a mujoco_ros2_control node is already up.

    Two controller_managers on one ROS graph is not a clean failure. Both advertise
    /controller_manager/load_controller, /configure_controller and /list_controllers, so each
    spawner request is answered by whichever responds first -- which means one request lands on
    the old manager and the next on the new one. What you get is ~200 lines of mutually
    contradictory output: "Controller already loaded, skipping load_controller" from the manager
    that has them, "no controller with this name exists" from the manager that does not, and a
    controller logging "configure successful" while its own spawner reports "Failed to configure
    controller". None of those messages mentions the actual problem, and every one of them points
    at the controller config instead.
    """
    import subprocess
    found = subprocess.run(["pgrep", "-f", "mujoco_ros2_control/ros2_control_node"],
                           capture_output=True, text=True).stdout.split()
    if found:
        pids = ' '.join(found)
        raise RuntimeError(
            'a mujoco_ros2_control node is ALREADY RUNNING (pid ' + pids + '). Two '
            'controller_managers on one ROS graph answer each other service calls, so '
            'every spawner fails with a misleading message. Stop it first:  kill ' + pids)
    return []


def generate_launch_description() -> LaunchDescription:
    desc = FindPackageShare("zero_description")
    bringup = FindPackageShare("zero_bringup")
    urdf = PathJoinSubstitution([desc, "urdf", "zero_panda.urdf"])
    controllers = PathJoinSubstitution([bringup, "config", "panda_controllers.yaml"])
    control_params = PathJoinSubstitution([bringup, "config", "panda_control.yaml"])

    rsp = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[{"robot_description":
                     ParameterValue(Command(["xacro ", urdf]), value_type=str)}],
    )
    ctrl = Node(
        package="mujoco_ros2_control",
        executable="ros2_control_node",
        output="screen",
        parameters=[controllers],
    )
    spawners = [
        Node(package="controller_manager", executable="spawner",
             arguments=[n, "--controller-manager", "/controller_manager"], output="screen")
        for n in CONTROLLERS
    ]
    # SE(3) -> joint IK. Starts alongside the spawners; it holds the measured configuration until
    # a /zero/eef_target arrives, so ordering against the controllers does not matter.
    eef = Node(
        package="zero_control", executable="eef_control", output="screen",
        parameters=[control_params],
    )
    return LaunchDescription([
        OpaqueFunction(function=_preflight),
        rsp, ctrl,
        RegisterEventHandler(OnProcessStart(target_action=ctrl, on_start=spawners + [eef])),
    ])
