"""Bring up the ZERO rebot dual-arm workstation in MuJoCo under ros2_control.

GENERATED by scripts/gen_bringup.py rebot -- edit the generator, not this file.

PIPELINE:
  1. robot_state_publisher puts the URDF on /robot_description. It goes through XACRO, which is
     load-bearing: the URDF's `mujoco_model` param uses `$(find zero_description)/...`, and only
     xacro expands that into an absolute path. mujoco_ros2_control does NOT resolve package://
     and dies with "MuJoCo model file 'package://...' does not exist!".
  2. mujoco_ros2_control's OWN ros2_control_node (not controller_manager's) loads the MJCF named
     by that param and starts the sim.
  3. Controllers spawn once the node is up -- joint_state_broadcaster first, or the position
     controllers activate with no state interfaces to read and immediately fault.

Cameras: 5 MJCF cameras are published because the URDF declares a matching <sensor> for
each (top, front, side, left_wrist, right_wrist). View them in RViz on /zero/<cam>/image_raw.

Run:  ros2 launch zero_bringup rebot.launch.py
"""

from launch import LaunchDescription
from launch.actions import RegisterEventHandler
from launch.event_handlers import OnProcessStart
from launch.substitutions import Command, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare

CONTROLLERS = ['joint_state_broadcaster', 'left_arm_controller', 'left_gripper_controller', 'right_arm_controller', 'right_gripper_controller']


def generate_launch_description() -> LaunchDescription:
    desc = FindPackageShare("zero_description")
    bringup = FindPackageShare("zero_bringup")
    urdf = PathJoinSubstitution([desc, "urdf", "zero_rebot.urdf"])
    controllers = PathJoinSubstitution([bringup, "config", "rebot_controllers.yaml"])

    rsp = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[{"robot_description":
                     ParameterValue(Command(["xacro ", urdf]), value_type=str)}],
    )
    ctrl = Node(
        package="mujoco_ros2_control",
        executable="ros2_control_node",
        output="screen",
        parameters=[controllers],
    )
    spawners = [
        Node(package="controller_manager", executable="spawner",
             arguments=[n, "--controller-manager", "/controller_manager"], output="screen")
        for n in CONTROLLERS
    ]
    return LaunchDescription([
        rsp, ctrl,
        RegisterEventHandler(OnProcessStart(target_action=ctrl, on_start=spawners)),
    ])
