"""ZERO end-effector control node: SE(3) targets -> joint commands, for any embodiment.

    ros2 run zero_control eef_control --ros-args -p robot:=rebot

SUBSCRIBES
    /joint_states            sensor_msgs/JointState      current configuration
    /zero/eef_target         Float64MultiArray[20]       the action: per hand pos3+rot6d+grip1
PUBLISHES
    /{side}_arm_controller/commands      Float64MultiArray   joint positions
    /{side}_gripper_controller/commands  Float64MultiArray   joint positions
    /zero/ik_status                      Float64MultiArray[6]  see below

ONE NODE, EVERY ROBOT. Nothing here is reBot- or Panda-specific: joint names, EEF frame, gripper
range and URDF all come from `zero_layout.ROBOTS[robot]`. That is deliberate -- if the source and
target embodiments ran different control code, an implementation difference could masquerade as a
transfer result, and the transfer number is the entire point of the project.

/zero/ik_status IS NOT OPTIONAL: [left_pos_err, left_rot_err, left_clamped,
right_pos_err, right_rot_err, right_clamped]. An unreachable target does not raise -- IK returns
a large residual and a clamped step, the arm stalls short, and it looks exactly like the policy
failing. On the previous project that misdiagnosis cost days: the giveaway (a closest-approach
distance pinned at the same value across every hyperparameter) was read as a learning problem for
far too long. Log it, always.

STARTUP HOLDS HOME, NOT THE MEASUREMENT. Until a target arrives the node commands the `home`
configuration from the registry. Commanding the measured configuration instead looks safer -- it
cannot snap on launch -- but it is a creep: a position command equal to where the arm already is
exerts no restoring force, so gravity pulls it a little further every tick and the sagged pose
becomes the next command. Measured here: a monotonic 0.64 -> 0.70 rad drift from home over 45 s,
still climbing, with no equilibrium. It also cost a day of debugging. An EEF target computed from
the home keyframe was 574 mm from a right arm that had quietly crept away, which reads exactly
like an IK or controller fault -- the solver, the joint limits and the MuJoCo closed loop all
tested clean in isolation. Holding a fixed reference also makes the start pose repeatable across
episodes, which the dataset needs.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pinocchio as pin
import rclpy
from ament_index_python.packages import get_package_share_directory
from rclpy.node import Node
from sensor_msgs.msg import JointState
from std_msgs.msg import Float64MultiArray

from zero_control.action import DIM, SIDES, pack, unpack
from zero_control.ik import ArmIK


class EefControlNode(Node):
    def __init__(self) -> None:
        super().__init__("zero_eef_control")
        # Everything robot-specific arrives as PARAMETERS, generated from zero_layout.ROBOTS by
        # scripts/gen_bringup.py into config/<robot>_control.yaml. The node imports nothing from
        # the repo, so it behaves identically from source or from an install tree -- and
        # zero_layout stays the single source of truth.
        self.declare_parameter("robot", "rebot")
        self.declare_parameter("rate_hz", 100.0)
        self.declare_parameter("damping", 0.05)
        self.declare_parameter("gain", 1.0)
        self.declare_parameter("dq_max", 0.05)
        self.declare_parameter("eef_offset", [0.0, 0.0, 0.0])
        self.declare_parameter("grip_range", [0.0, 0.04])
        self.declare_parameter("grip_ctrl_n", 1)
        for side in SIDES:
            self.declare_parameter(f"{side}_arm_joints", [""])
            self.declare_parameter(f"{side}_eef_frame", "")
            self.declare_parameter(f"{side}_home", [0.0])

        key = self.get_parameter("robot").value
        urdf = str(Path(get_package_share_directory("zero_description"))
                   / "urdf" / f"zero_{key}.urdf")
        eef_offset = tuple(self.get_parameter("eef_offset").value)

        self.ik: dict[str, ArmIK] = {}
        self.arm_pub: dict[str, object] = {}
        self.grip_pub: dict[str, object] = {}
        self.arm_joints: dict[str, list[str]] = {}
        self.home: dict[str, np.ndarray] = {}
        for side in SIDES:
            jn = list(self.get_parameter(f"{side}_arm_joints").value)
            frame = self.get_parameter(f"{side}_eef_frame").value
            if not jn or not jn[0] or not frame:
                raise SystemExit(
                    f"missing params for {side}: pass config/{key}_control.yaml "
                    f"(generated by scripts/gen_bringup.py)")
            self.arm_joints[side] = jn
            self.home[side] = np.asarray(
                self.get_parameter(f"{side}_home").value, dtype=float)
            if len(self.home[side]) != len(jn):
                raise SystemExit(
                    f"{side}_home has {len(self.home[side])} values, expected {len(jn)}")
            self.ik[side] = ArmIK(
                urdf, frame, jn, eef_offset,
                damping=self.get_parameter("damping").value,
                gain=self.get_parameter("gain").value,
                dq_max=self.get_parameter("dq_max").value)
            self.arm_pub[side] = self.create_publisher(
                Float64MultiArray, f"/{side}_arm_controller/commands", 10)
            self.grip_pub[side] = self.create_publisher(
                Float64MultiArray, f"/{side}_gripper_controller/commands", 10)

        self.grip_ctrl_n = int(self.get_parameter("grip_ctrl_n").value)
        self.grip_lo, self.grip_hi = tuple(self.get_parameter("grip_range").value)

        self.q = np.zeros(self.ik["left"].model.nq)   # full-model config, kept in sync
        self.q_meas = np.zeros(self.ik["left"].model.nq)  # PURE measurement, for /zero/eef_state
        self.have_js = False
        self.target: np.ndarray | None = None

        self.create_subscription(JointState, "/joint_states", self._on_js, 10)
        self.create_subscription(Float64MultiArray, "/zero/eef_target", self._on_target, 10)
        self.status_pub = self.create_publisher(Float64MultiArray, "/zero/ik_status", 10)
        # The MEASURED 20-dim observation, for consumers that must not duplicate the kinematics.
        # policy_node needs this: it runs under lerobot_env, whose numpy 2.x cannot load ROS's
        # pinocchio (built against numpy 1.x), so it cannot do its own FK. Publishing it here
        # also keeps this node the single source of FK truth, rather than a second
        # implementation that could drift from the one the dataset was recorded with.
        self.state_pub = self.create_publisher(Float64MultiArray, "/zero/eef_state", 10)

        hz = float(self.get_parameter("rate_hz").value)
        self.timer = self.create_timer(1.0 / hz, self._tick)
        self.get_logger().info(
            f"robot={key}  urdf={Path(urdf).name}  nq={self.ik['left'].model.nq}  "
            f"eef={[self.get_parameter(f'{s}_eef_frame').value for s in SIDES]}  {hz:.0f} Hz")

    # ---------------------------------------------------------------- callbacks
    def _on_js(self, msg: JointState) -> None:
        """Mirror measured joint positions into the pinocchio configuration vector.

        Matching BY NAME, not by index: /joint_states ordering is whatever the broadcaster emits
        and is not guaranteed to match the URDF's joint order.
        """
        model = self.ik["left"].model
        for name, pos in zip(msg.name, msg.position):
            jid = model.getJointId(name)
            if jid < model.njoints:
                self.q[model.joints[jid].idx_q] = pos
                self.q_meas[model.joints[jid].idx_q] = pos
        self.have_js = True
        self._publish_state()

    def _on_target(self, msg: Float64MultiArray) -> None:
        if len(msg.data) != DIM:
            self.get_logger().warn(f"/zero/eef_target has {len(msg.data)} values, expected {DIM}")
            return
        self.target = np.asarray(msg.data, dtype=float)

    # ---------------------------------------------------------------- control loop
    def _tick(self) -> None:
        if not self.have_js:
            return
        if self.target is None:
            # Hold HOME, not the measurement -- see the module docstring. Commanding the measured
            # configuration is a gravity creep with no equilibrium.
            for side in SIDES:
                self._publish_arm(side, self.home[side])
            return

        poses, grips = unpack(self.target)
        status: list[float] = []
        for side in SIDES:
            ik = self.ik[side]
            pos, R = poses[side]
            res = ik.step(self.q, pin.SE3(R, np.asarray(pos, dtype=float)))
            self.q[ik.qidx] = res.q[ik.qidx]
            self._publish_arm(side, res.q[ik.qidx])
            self._publish_grip(side, grips[side])
            status += [res.pos_err, res.rot_err, float(res.clamped)]
        self.status_pub.publish(Float64MultiArray(data=status))

    def _publish_state(self) -> None:
        """Publish the measured 20-dim observation, identical to record_node._measured_state.

        Poses are FK on the MEASURED joints (self.q_meas, not self.q -- the latter carries the
        servo's own IK result). Grip channels are the LAST COMMANDED grip, not a sensor, because
        that is what the recorder stored and therefore what a policy trained against.
        """
        fk = {s: self.ik[s].fk(self.q_meas) for s in SIDES}      # once per side, at 100 Hz
        poses = {s: (fk[s].translation, fk[s].rotation) for s in SIDES}
        grips = {s: (float(self.target[9 if s == "left" else 19])
                     if self.target is not None else 0.0) for s in SIDES}
        self.state_pub.publish(Float64MultiArray(
            data=[float(v) for v in pack(poses, grips)]))

    def _publish_arm(self, side: str, q_arm: np.ndarray) -> None:
        self.arm_pub[side].publish(Float64MultiArray(data=[float(v) for v in q_arm]))

    def _publish_grip(self, side: str, grip: float) -> None:
        # grip is normalised [0,1]; 0 = closed, 1 = open. One value per COMMANDED gripper joint,
        # which is 2 on the reBot (two real actuators) and 1 on Panda (one actuator drives both
        # fingers through an <equality>).
        g = self.grip_lo + float(np.clip(grip, 0.0, 1.0)) * (self.grip_hi - self.grip_lo)
        self.grip_pub[side].publish(Float64MultiArray(data=[g] * self.grip_ctrl_n))


def main() -> None:
    rclpy.init()
    node = EefControlNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.try_shutdown()


if __name__ == "__main__":
    main()
