"""Generate controller YAML + launch file per embodiment.

    python scripts/gen_bringup.py rebot
    python scripts/gen_bringup.py panda

CONTROLLER CHOICE: `position_controllers/JointGroupPositionController`, NOT
JointTrajectoryController. JTC is for planned trajectories -- it interpolates to a goal and a
new goal preempts the old one, which fights a teleop loop streaming a fresh target every tick.
JointGroupPositionController takes a raw Float64MultiArray of positions, which is exactly what a
teleop/IK node publishes. This is the pattern from siddarth09/Panda_mujoco, already proven under
mujoco_ros2_control.

FOUR controllers, not two: one arm + one gripper PER SIDE. The arms are independent kinematic
chains, so a single controller spanning both would force joint planning; and a gripper sharing a
controller with its arm cannot be commanded while the arm is moving.

⚠️ Gripper joints are per-ACTUATOR, from the registry: the reBot has two real gripper actuators
(plus an <equality> coupling the fingers) so both are listed; Panda has ONE actuator driving both
fingers, so only `finger_joint1` is. Copying either pattern to the other robot is wrong.
"""

from __future__ import annotations

import sys

import zero_layout as L

BRINGUP = L.PKG.parent / "zero_bringup"


def controllers_yaml(key: str) -> str:
    r = L.ROBOTS[key]
    lines = [
        f"# GENERATED by scripts/gen_bringup.py {key} -- edit the generator, not this file.",
        "#",
        "# Every joint here must also appear in the URDF <ros2_control> block and the MJCF.",
        "# scripts/check_parity.py asserts that; a mismatch does not error, the joint just",
        "# silently never moves.",
        "",
        "controller_manager:",
        "  ros__parameters:",
        "    update_rate: 100",
        "",
        "    joint_state_broadcaster:",
        "      type: joint_state_broadcaster/JointStateBroadcaster",
        "",
    ]
    names = []
    for side in L.SIDES:
        for kind in ("arm", "gripper"):
            n = f"{side}_{kind}_controller"
            names.append(n)
            lines += [f"    {n}:",
                      "      type: position_controllers/JointGroupPositionController", ""]
    for side in L.SIDES:
        for kind, joints in (("arm", r["arm_ctrl_joints"]), ("gripper", r["grip_ctrl_joints"])):
            lines += [f"{side}_{kind}_controller:", "  ros__parameters:", "    joints:"]
            lines += [f"      - {L.prefixed(side, j)}" for j in joints]
            lines += ["    command_interfaces:", "      - position",
                      "    state_interfaces:", "      - position", "      - velocity", ""]
    return "\n".join(lines), names


LAUNCH = '''"""Bring up the ZERO {key} dual-arm workstation in MuJoCo under ros2_control.

GENERATED by scripts/gen_bringup.py {key} -- edit the generator, not this file.

PIPELINE:
  1. robot_state_publisher puts the URDF on /robot_description. It goes through XACRO, which is
     load-bearing: the URDF's `mujoco_model` param uses `$(find zero_description)/...`, and only
     xacro expands that into an absolute path. mujoco_ros2_control does NOT resolve package://
     and dies with "MuJoCo model file 'package://...' does not exist!".
  2. mujoco_ros2_control's OWN ros2_control_node (not controller_manager's) loads the MJCF named
     by that param and starts the sim.
  3. Controllers spawn once the node is up -- joint_state_broadcaster first, or the position
     controllers activate with no state interfaces to read and immediately fault.

Cameras: {ncam} MJCF cameras are published because the URDF declares a matching <sensor> for
each ({cams}). View them in RViz on {ns}/<cam>/image_raw.

Run:  ros2 launch zero_bringup {key}.launch.py
"""

from launch import LaunchDescription
from launch.actions import RegisterEventHandler
from launch.event_handlers import OnProcessStart
from launch.substitutions import Command, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare

CONTROLLERS = {controllers!r}


def generate_launch_description() -> LaunchDescription:
    desc = FindPackageShare("zero_description")
    bringup = FindPackageShare("zero_bringup")
    urdf = PathJoinSubstitution([desc, "urdf", "zero_{key}.urdf"])
    controllers = PathJoinSubstitution([bringup, "config", "{key}_controllers.yaml"])

    rsp = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[{{"robot_description":
                     ParameterValue(Command(["xacro ", urdf]), value_type=str)}}],
    )
    ctrl = Node(
        package="mujoco_ros2_control",
        executable="ros2_control_node",
        output="screen",
        parameters=[controllers],
    )
    spawners = [
        Node(package="controller_manager", executable="spawner",
             arguments=[n, "--controller-manager", "/controller_manager"], output="screen")
        for n in CONTROLLERS
    ]
    return LaunchDescription([
        rsp, ctrl,
        RegisterEventHandler(OnProcessStart(target_action=ctrl, on_start=spawners)),
    ])
'''


def main() -> None:
    key = sys.argv[1] if len(sys.argv) > 1 else "rebot"
    if key not in L.ROBOTS:
        raise SystemExit(f"unknown robot {key!r}")
    yaml_txt, names = controllers_yaml(key)
    (BRINGUP / "config").mkdir(parents=True, exist_ok=True)
    (BRINGUP / "launch").mkdir(parents=True, exist_ok=True)
    ycfg = BRINGUP / "config" / f"{key}_controllers.yaml"
    ycfg.write_text(yaml_txt)
    lp = BRINGUP / "launch" / f"{key}.launch.py"
    lp.write_text(LAUNCH.format(key=key, controllers=["joint_state_broadcaster"] + names,
                                ncam=len(L.all_cameras()), cams=", ".join(L.all_cameras()),
                                ns=L.CAM_NS))
    print(f"[{key}] wrote {ycfg.name} ({len(names)} controllers) + {lp.name}")
    print(f"  controllers: {names}")


if __name__ == "__main__":
    main()
