"""Generate controller YAML + launch file per embodiment.

    python scripts/gen_bringup.py rebot
    python scripts/gen_bringup.py panda

CONTROLLER CHOICE: `position_controllers/JointGroupPositionController`, NOT
JointTrajectoryController. JTC is for planned trajectories -- it interpolates to a goal and a
new goal preempts the old one, which fights a teleop loop streaming a fresh target every tick.
JointGroupPositionController takes a raw Float64MultiArray of positions, which is exactly what a
teleop/IK node publishes. This is the pattern from siddarth09/Panda_mujoco, already proven under
mujoco_ros2_control.

FOUR controllers, not two: one arm + one gripper PER SIDE. The arms are independent kinematic
chains, so a single controller spanning both would force joint planning; and a gripper sharing a
controller with its arm cannot be commanded while the arm is moving.

⚠️ Gripper joints are per-ACTUATOR, from the registry: the reBot has two real gripper actuators
(plus an <equality> coupling the fingers) so both are listed; Panda has ONE actuator driving both
fingers, so only `finger_joint1` is. Copying either pattern to the other robot is wrong.
"""

from __future__ import annotations

import sys

import mujoco

import zero_layout as L

BRINGUP = L.PKG.parent / "zero_bringup"


def controllers_yaml(key: str) -> str:
    r = L.ROBOTS[key]
    lines = [
        f"# GENERATED by scripts/gen_bringup.py {key} -- edit the generator, not this file.",
        "#",
        "# Every joint here must also appear in the URDF <ros2_control> block and the MJCF.",
        "# scripts/check_parity.py asserts that; a mismatch does not error, the joint just",
        "# silently never moves.",
        "",
        "controller_manager:",
        "  ros__parameters:",
        "    update_rate: 100",
        "",
        "    joint_state_broadcaster:",
        "      type: joint_state_broadcaster/JointStateBroadcaster",
        "",
    ]
    names = []
    for side in L.SIDES:
        for kind in ("arm", "gripper"):
            n = f"{side}_{kind}_controller"
            names.append(n)
            lines += [f"    {n}:",
                      "      type: position_controllers/JointGroupPositionController", ""]
    for side in L.SIDES:
        for kind, joints in (("arm", r["arm_ctrl_joints"]), ("gripper", r["grip_ctrl_joints"])):
            lines += [f"{side}_{kind}_controller:", "  ros__parameters:", "    joints:"]
            lines += [f"      - {L.prefixed(side, j)}" for j in joints]
            lines += ["    command_interfaces:", "      - position",
                      "    state_interfaces:", "      - position", "      - velocity", ""]
    return "\n".join(lines), names


LAUNCH = '''"""Bring up the ZERO {key} dual-arm workstation in MuJoCo under ros2_control.

GENERATED by scripts/gen_bringup.py {key} -- edit the generator, not this file.

PIPELINE:
  1. robot_state_publisher puts the URDF on /robot_description. It goes through XACRO, which is
     load-bearing: the URDF's `mujoco_model` param uses `$(find zero_description)/...`, and only
     xacro expands that into an absolute path. mujoco_ros2_control does NOT resolve package://
     and dies with "MuJoCo model file 'package://...' does not exist!".
  2. mujoco_ros2_control's OWN ros2_control_node (not controller_manager's) loads the MJCF named
     by that param and starts the sim.
  3. Controllers spawn once the node is up -- joint_state_broadcaster first, or the position
     controllers activate with no state interfaces to read and immediately fault.

Cameras: {ncam} MJCF cameras are published because the URDF declares a matching <sensor> for
each ({cams}). View them in RViz on {ns}/<cam>/image_raw.

Run:  ros2 launch zero_bringup {key}.launch.py
"""

from launch import LaunchDescription
from launch.actions import RegisterEventHandler
from launch.event_handlers import OnProcessStart
from launch.substitutions import Command, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare

CONTROLLERS = {controllers!r}


def generate_launch_description() -> LaunchDescription:
    desc = FindPackageShare("zero_description")
    bringup = FindPackageShare("zero_bringup")
    urdf = PathJoinSubstitution([desc, "urdf", "zero_{key}.urdf"])
    controllers = PathJoinSubstitution([bringup, "config", "{key}_controllers.yaml"])
    control_params = PathJoinSubstitution([bringup, "config", "{key}_control.yaml"])

    rsp = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[{{"robot_description":
                     ParameterValue(Command(["xacro ", urdf]), value_type=str)}}],
    )
    ctrl = Node(
        package="mujoco_ros2_control",
        executable="ros2_control_node",
        output="screen",
        parameters=[controllers],
    )
    spawners = [
        Node(package="controller_manager", executable="spawner",
             arguments=[n, "--controller-manager", "/controller_manager"], output="screen")
        for n in CONTROLLERS
    ]
    # SE(3) -> joint IK. Starts alongside the spawners; it holds the measured configuration until
    # a /zero/eef_target arrives, so ordering against the controllers does not matter.
    eef = Node(
        package="zero_control", executable="eef_control", output="screen",
        parameters=[control_params],
    )
    return LaunchDescription([
        rsp, ctrl,
        RegisterEventHandler(OnProcessStart(target_action=ctrl, on_start=spawners + [eef])),
    ])
'''


def control_yaml(key: str) -> str:
    """Params for zero_control's nodes, generated from the registry.

    The nodes must not import zero_layout: once installed, the repo's scripts/ dir is on no path.
    Emitting params keeps zero_layout as the single source of truth while letting them run
    identically from source or from an install tree.

    TWO SECTIONS, and the split matters. The kinematic description -- EEF frames, arm joint
    names, tool offset, gripper range -- goes under the `/**` wildcard because it describes the
    ROBOT, not any one node: eef_control, servo_test, the teleop node and the dataset writer all
    need identical values, and a per-node copy is a silent divergence waiting to happen. Only the
    servo GAINS, genuinely eef_control's business, stay namespaced. Namespacing the frames
    instead makes every other node load with `left_eef_frame=""` and fail in the IK constructor.
    """
    r = L.ROBOTS[key]
    lines = [
        f"# GENERATED by scripts/gen_bringup.py {key} -- edit the generator, not this file.",
        "",
        "# Shared robot description -- every zero_control node reads these.",
        "/**:",
        "  ros__parameters:",
        f"    robot: {key}",
        f"    eef_offset: [{', '.join(f'{v}' for v in r['eef_offset'])}]",
        f"    grip_range: [{r['grip_range'][0]}, {r['grip_range'][1]}]",
        f"    grip_ctrl_n: {len(r['grip_ctrl_joints'])}",
    ]
    # Task landmark positions, read from the COMPILED scene rather than restated here. The
    # objects rest where their measured geometry puts them, so any constant written by hand is a
    # second source of truth that silently goes stale the moment an asset or the table changes.
    mjcf = L.PKG / "mjcf" / f"zero_{key}.xml"
    if mjcf.exists():
        m = mujoco.MjModel.from_xml_path(str(mjcf))
        d = mujoco.MjData(m)
        mujoco.mj_resetDataKeyframe(m, d, mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_KEY, "home"))
        mujoco.mj_forward(m, d)

        def extent(body: str) -> tuple:
            """(origin, lowest, highest) z of a body's COLLISION geometry, from mesh vertices."""
            bid = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_BODY, body)
            assert bid >= 0, f"{body} missing from {mjcf.name}"
            zlo, zhi = float("inf"), float("-inf")
            for g in range(m.body_geomadr[bid], m.body_geomadr[bid] + m.body_geomnum[bid]):
                if not (m.geom_contype[g] or m.geom_conaffinity[g]):
                    continue
                if m.geom_type[g] == mujoco.mjtGeom.mjGEOM_MESH:
                    mid = m.geom_dataid[g]
                    V = m.mesh_vert[m.mesh_vertadr[mid]:
                                    m.mesh_vertadr[mid] + m.mesh_vertnum[mid]].reshape(-1, 3)
                    W = (d.geom_xmat[g].reshape(3, 3) @ V.T).T + d.geom_xpos[g]
                    zlo, zhi = min(zlo, W[:, 2].min()), max(zhi, W[:, 2].max())
                else:
                    zlo = min(zlo, d.geom_xpos[g][2] - m.geom_size[g][2])
                    zhi = max(zhi, d.geom_xpos[g][2] + m.geom_size[g][2])
            return d.xpos[bid].copy(), zlo, zhi

        obj_o, obj_lo, obj_hi = extent("obj_object")
        tray_o, tray_lo, tray_hi = extent("plate_object")

        # PICK: the object's own centre -- that is where a gripper closes on it.
        lines.append("    pick_xyz: [" + ", ".join(f"{v:.5f}" for v in obj_o) + "]")

        # PLACE: NOT the tray's body origin. That origin sits ~3 mm above the table, i.e. INSIDE
        # the tray, so servoing the gripper's pinch point to it means driving through the tray
        # floor. Physics stops the arm ~48 mm short and it reads as an IK failure -- and a
        # kinematics-only reachability check will happily call it reachable, because ik.step knows
        # nothing about collision. The release point is above the RIM, offset by half the carried
        # object's height plus clearance.
        place_z = tray_hi + (obj_hi - obj_lo) / 2.0 + 0.010
        lines.append(f"    place_xyz: [{tray_o[0]:.5f}, {tray_o[1]:.5f}, {place_z:.5f}]")
        lines.append(f"    # tray rim top {tray_hi:.5f}, object height {obj_hi - obj_lo:.5f}")

    for side in L.SIDES:
        lines.append(f"    {side}_eef_frame: {r['urdf_eef_frame'].format(side=side)}")
        js = ", ".join(f'"{L.prefixed(side, j)}"' for j in r["arm_joints"])
        lines.append(f"    {side}_arm_joints: [{js}]")
        hs = ", ".join(f"{v}" for v in r["home"][side])
        lines.append(f"    {side}_home: [{hs}]")
    lines += [
        "",
        "# Servo gains -- eef_control's own.",
        "zero_eef_control:",
        "  ros__parameters:",
        "    rate_hz: 100.0",
        "    damping: 0.05          # DLS lambda; reBot is 6-DoF so J is square and needs this",
        "    gain: 1.0",
        "    dq_max: 0.05           # rad per tick, bounds the step near singularities",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    key = sys.argv[1] if len(sys.argv) > 1 else "rebot"
    if key not in L.ROBOTS:
        raise SystemExit(f"unknown robot {key!r}")
    yaml_txt, names = controllers_yaml(key)
    (BRINGUP / "config").mkdir(parents=True, exist_ok=True)
    (BRINGUP / "launch").mkdir(parents=True, exist_ok=True)
    ycfg = BRINGUP / "config" / f"{key}_controllers.yaml"
    ycfg.write_text(yaml_txt)
    ccfg = BRINGUP / "config" / f"{key}_control.yaml"
    ccfg.write_text(control_yaml(key))
    lp = BRINGUP / "launch" / f"{key}.launch.py"
    lp.write_text(LAUNCH.format(key=key, controllers=["joint_state_broadcaster"] + names,
                                ncam=len(L.all_cameras()), cams=", ".join(L.all_cameras()),
                                ns=L.CAM_NS))
    print(f"[{key}] wrote {ycfg.name} ({len(names)} controllers) + {ccfg.name} + {lp.name}")
    print(f"  controllers: {names}")


if __name__ == "__main__":
    main()
